# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToDoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 715)
        MainWindow.setStyleSheet("border-radius: 50px;\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 691))
        self.frame.setStyleSheet("border-radius: 50px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.imagelabel = QtWidgets.QLabel(self.frame)
        self.imagelabel.setGeometry(QtCore.QRect(90, 50, 251, 81))
        self.imagelabel.setText("")
        self.imagelabel.setPixmap(QtGui.QPixmap(":/images/Screenshot 2025-05-13 140447.jpg"))
        self.imagelabel.setScaledContents(True)
        self.imagelabel.setObjectName("imagelabel")
        self.exitbutton = QtWidgets.QPushButton(self.frame)
        self.exitbutton.setGeometry(QtCore.QRect(50, 10, 16, 16))
        self.exitbutton.setMinimumSize(QtCore.QSize(16, 16))
        self.exitbutton.setMaximumSize(QtCore.QSize(16, 16))
        self.exitbutton.setStyleSheet("border-radius: 8px;\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"hover {\n"
"    background-color: #45a049;\n"
"}")
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")
        self.minimizebutton = QtWidgets.QPushButton(self.frame)
        self.minimizebutton.setGeometry(QtCore.QRect(90, 10, 16, 16))
        self.minimizebutton.setMinimumSize(QtCore.QSize(16, 16))
        self.minimizebutton.setMaximumSize(QtCore.QSize(16, 16))
        self.minimizebutton.setStyleSheet("border-radius: 8px;\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.minimizebutton.setText("")
        self.minimizebutton.setObjectName("minimizebutton")
        self.expandbutton = QtWidgets.QPushButton(self.frame)
        self.expandbutton.setGeometry(QtCore.QRect(70, 10, 16, 16))
        self.expandbutton.setMinimumSize(QtCore.QSize(16, 16))
        self.expandbutton.setMaximumSize(QtCore.QSize(16, 16))
        self.expandbutton.setStyleSheet("border-radius: 8px;\n"
"background-color: rgb(255, 255, 0);\n"
"")
        self.expandbutton.setText("")
        self.expandbutton.setObjectName("expandbutton")
        self.inputtask = QtWidgets.QLineEdit(self.frame)
        self.inputtask.setGeometry(QtCore.QRect(30, 180, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        self.inputtask.setFont(font)
        self.inputtask.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 15px;\n"
"")
        self.inputtask.setText("")
        self.inputtask.setObjectName("inputtask")
        self.addtaskbutton = QtWidgets.QPushButton(self.frame)
        self.addtaskbutton.setGeometry(QtCore.QRect(350, 180, 41, 41))
        self.addtaskbutton.setStyleSheet("\n"
"")
        self.addtaskbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons8_macos_maximize_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addtaskbutton.setIcon(icon)
        self.addtaskbutton.setIconSize(QtCore.QSize(50, 50))
        self.addtaskbutton.setObjectName("addtaskbutton")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(20, 240, 391, 1))
        self.line.setStyleSheet("color: rgb(213, 213, 213);\n"
"background-color: rgb(198, 198, 198);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(30, 260, 361, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 361, 361))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.taskListContainer = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.taskListContainer.setGeometry(QtCore.QRect(0, 0, 361, 361))
        self.taskListContainer.setObjectName("taskListContainer")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.taskListContainer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.taskListLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.taskListLayout.setContentsMargins(5, 0, 0, 0)
        self.taskListLayout.setObjectName("taskListLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.deletetaskbutton = QtWidgets.QPushButton(self.frame)
        self.deletetaskbutton.setGeometry(QtCore.QRect(360, 640, 41, 41))
        self.deletetaskbutton.setStyleSheet("")
        self.deletetaskbutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons8_Delete_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletetaskbutton.setIcon(icon1)
        self.deletetaskbutton.setIconSize(QtCore.QSize(50, 50))
        self.deletetaskbutton.setObjectName("deletetaskbutton")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(20, 630, 391, 1))
        self.line_2.setStyleSheet("color: rgb(213, 213, 213);\n"
"background-color: rgb(198, 198, 198);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.savetasks = QtWidgets.QPushButton(self.frame)
        self.savetasks.setGeometry(QtCore.QRect(30, 650, 111, 28))
        self.savetasks.setStyleSheet("\n"
"border-radius: 10px;\n"
"border: 1px solid gray;")
        self.savetasks.setObjectName("savetasks")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputtask.setPlaceholderText(_translate("MainWindow", "Add new to do"))
        self.savetasks.setText(_translate("MainWindow", "save tasks"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
import todoimages


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
